### ISSUE TITLE
Bug: Same fingerprint to user that use iPhone

### ISSUE THREAD

**Issue by juanurcola** [Rajesh-Royal/Broprint.js#3]
I could to see that users who have iphone, always generate the same fingerprint 

5950378396046291

I tested in differente iphones and browsers (safari and chrome)

### **Step to reproduce**
1. Go to the website https://broprintjs.netlify.app/ from a iphone (using chrome o safari)
2. Click on Generate FingerPrint Button

**Comment by geekhunger** [comment]
> I could to see that users who have iphone, always generate the same fingerprint
> 
> 5950378396046291
> 
> I tested in differente iphones and browsers (safari and chrome)
> 
> ### **Step to reproduce**
> 1. Go to the website https://broprintjs.netlify.app/ from a iphone (using chrome o safari)
> 2. Click on Generate FingerPrint Button

My iPhones received the exact same fingerprint as yours! Very interesting find!

At first, I didn't notice that my ID was the same as yours and I was thinking it's because of my iPhones going through the same network. Must be a bug then, I guess (or Safari has implemented new defense methods against fingerprinting with Canvas/Audio).

**Comment by larinius** [comment]
Chrome, Edge - same issue
![image](https://user-images.githubusercontent.com/5310985/196040632-0d9a6d3c-d206-4e0a-94d5-51be11b006d3.png)

**Comment by abhishek77in** [comment]
Oh! I thought this was a really promising library.

**Comment by abhishek77in** [comment]
Is this is a real issue, this point (this post) should be highlighted in the REAME instead of saying this library is only for educational purposes.

**Comment by paulvl** [comment]
Even fingerprintjs pro have issues with Edge, you cant test it https://fingerprint.com/demo/

**Comment by claysam75** [comment]
I also see exactly the same fingerprint when using an iphone. Such a shame, I would have replaced fingerprintjs with this in a heartbeat otherwise.

**Comment by anelad** [comment]
Yep, same here, at least for my iPhone. My girlfriends' iPhone gives a different one tho

**Comment by Rajesh-Royal** [comment]
Not sure what is the actual issue, but I was thinking of implementing a tracking option to track unique users by their IP address using [ipify](https://api.ipify.org/?format=jsonp&callback=?). But again It can have less accuracy if the user started using a VPN.

If anyone has any suggestions or ideas please share.

**Comment by jalsco** [comment]
So it isn't working... 😢
Such a shame - I wanted to use this library  ! It looks perfect, and also easy to implement. 
But requirement, obviously, is that each Visitor device gets a unique I

**Comment by Rajesh-Royal** [comment]
No fix available as of now, open to accept PR.

**Comment by jalsco** [comment]
ok - hopefully the library can be improved at a later date. All respect to you ! 🙏🏻 I will keep a watch on this project, so much promise here, and is already so very close !

Like many, my needs are to (within statistical reasonableness) detect UNIQUE device/browser visitors. So at this time this library cannot be used for that. Thanks for replying 🙏🏻
