### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by r0x0r** [Rajesh-Royal/Broprint.js#4]
How does this compare to fingerprint js (pro) in terms of accuracy?

**Comment by sanzhardanybayev** [comment]
@r0x0r `fingerprint` pro version must be having higher accuracy as it involves backend computations involved that uses IP address, region, country, and other additional properties of user's client.

**Comment by anelad** [comment]
FingerprintJS says in it's Github repo that the accuracy is between 40% - 60%, without server side computations of its Pro version; so we might expect a close accuracy range for this repo too.

**Comment by Rajesh-Royal** [comment]
@r0x0r Haven't compared this lib with fingerPrint.js or its Pro version yet. Will update the docs once I have done that, or I will be happy to request a PR for it.
