### ISSUE TITLE
README has typo

### ISSUE THREAD

**Issue by deadcoder0904** [Rajesh-Royal/Broprint.js#9]
```ts
import { getCurrentBrowserFingerPrint } from "npm i @rajesh896/broprint.js";
```

should be

```ts
import { getCurrentBrowserFingerPrint } from "@rajesh896/broprint.js";
```

**Comment by BenAHammond** [comment]
There's [an open PR for this](https://github.com/Rajesh-Royal/Broprint.js/pull/5). Not sure if it was intended or not at this point as its sitting untouched.

**Comment by Rajesh-Royal** [comment]
I will approve the PR after review. Thank you.

**Comment by Rajesh-Royal** [comment]
@deadcoder0904 @BenAHammond The PR #5 is merged. Thank you.
